### ISSUE TITLE
getPrice api

### ISSUE THREAD

**Issue by thanhnguyennguyen** [chaintex/TomoSwap#187]
we would like to create price alert function following price of Tomoswap. Could you please help to disclose getPrice api ?
expected response:
{ buyPrice: xxx, sellPrice: yyy}

**Comment by manhlx3006** [comment]
Hi, you can get price between TOMO-CONST from our proxy contract here by calling `getExpectedRate(srcToken, destToken, srcAmount)`:
Testnet: https://scan.testnet.tomochain.com/address/0x00252a171ee0ea54bfcf326c8cf86fd970205df0#code
Mainnet: https://scan.tomochain.com/address/0x668ef5D8e81Bc4A5755f425DB5A368e03686d2CF

Currently we don't have public API for getting rates or trading

**Comment by thanhnguyennguyen** [comment]
Cool, thank you !

**Comment by thanhnguyennguyen** [comment]
What is the assumption address of TOMO native ?

**Comment by thanhnguyennguyen** [comment]
is this one ?
https://github.com/chaintex/TomoSwap/blob/3fbbab777ca20e9f22b924442568c3a6c894f060/src/config/tokens.js#L5

**Comment by manhlx3006** [comment]
Yes, we use `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` as TOMO's address. Other tokens you can also find in the tokens config file.
branch `develop` for TOMO testnet's addresses, `master` for TOMO mainnet's addresses
